//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_SubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question_SubCategory()
        {
            this.Test_history = new HashSet<Test_history>();
        }
    
        public int question_subcategory_id { get; set; }
        public string question_subcategory_name { get; set; }
        public int question_maincategory { get; set; }
        public byte[] question_subcategory_image { get; set; }
    
        public virtual Question_main_category Question_main_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_history> Test_history { get; set; }
    }
}
