//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Test_history = new HashSet<Test_history>();
        }
    
        public int user_id { get; set; }
        public string user_login { get; set; }
        public string user_pass { get; set; }
        public int user_category { get; set; }
        public Nullable<int> user_birthyear { get; set; }
        public byte[] user_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_history> Test_history { get; set; }
        public virtual Users_category Users_category { get; set; }
    }
}
