//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyBaseNameEntities : DbContext
    {
        public MyBaseNameEntities()
            : base("name=MyBaseNameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Question_main_category> Question_main_category { get; set; }
        public virtual DbSet<Question_SubCategory> Question_SubCategory { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Test_history> Test_history { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_category> Users_category { get; set; }
        public virtual DbSet<History_answer> History_answer { get; set; }
    }
}
